<div class="container-fluid py-4 bg-gray-200">
    <div class="row mt-0">
        <div class="col-3 col-md-2 text-center">
            <img src="/oh/oh_dashboard.png" class="img-fluid" alt="main_logo">
        </div>
        <div class="col-12 col-md-12 text-center">
            <h5>TÉRMINOS DE LICENCIA Y CONDICIONES DE USO</h5>
        </div>
        <div class="col-12 col-md-12 text-start">
            Por favor, lea con atención los presentes términos de licencia y condiciones de uso (en adelante "el Acuerdo"), que regulan los términos de acceso y uso de la aplicación web OhMyPhoto, propiedad de SUPERQUBIT, S.L., con domicilio en C/ Alfonso X El Sabio, 13, 1ºA, C.P. 30205 de Cartagena (Murcia) y NIF B75321976, en adelante "la Empresa".   
            <h6 class="mt-2">1. ACEPTACIÓN DE TÉRMINOS Y CONDICIONES</h6>
        El usuario de la aplicación OhMyPhoto, así como la Empresa propietaria de la misma, podrán ser denominados conjuntamente como las partes.    El mero acceso o utilización de la aplicación, de todos o parte de sus contenidos y servicios, significa la aceptación plena y sin reservas de los presentes términos de licencia y condiciones de uso.  Si no está conforme con estos términos y condiciones y no los acepta expresamente, no acceda a la aplicación ni la use.
        <h6 class="mt-2">2. DESCRIPCIÓN DEL SERVICIO</h6>
        OhMyPhoto es una aplicación web para fotógrafos profesionales que proporciona a los fotógrafos herramientas para la gestión de sus bases de datos de clientes, catálogo propio de productos, firma de contratos en línea, reservas en línea y calendario, recepción de pagos, registro de ingresos y gastos y personalización básica de la plataforma para cada usuario.      OhMyPhoto no es un servicio de almacenamiento de imágenes en la nube, por lo que el usuario será responsable de conservar copia de los archivos que se suban en la aplicación para utilizar el servicio.   La empresa se reserva el derecho de realizar sin previo aviso actualizaciones o modificaciones en cualquiera de las herramientas que ofrece y el usuario renuncia expresamente a exigir cualquier responsabilidad o que las herramientas se restauren a su versión anterior.       Así mismo, la Empresa se reserva el derecho a establecer un coste adicional por futuras funcionalidades que pudiera incluir.
        <h6 class="mt-2">3. LICENCIA</h6>
        Mediante el presente Acuerdo, la Empresa otorga al usuario licencia y derecho de uso de la aplicación, limitados, no exclusivos e intransferibles, durante el periodo contratado en la suscripción y en los términos y condiciones establecidos en el mismo.   
        La aplicación se usa tal y como se suministra y no podrá ser modificada ni exigir modificaciones de la misma en ningún momento. Estos términos de uso también regirán sobre cualquiera de las actualizaciones de la aplicación que reemplacen y/o modifiquen a la aplicación original.
        <h6 class="mt-2">4. REQUISITOS</h6>
        Debe acceder a OhMyPhoto mediante una conexión a internet y desde un navegador compatible, siendo éste cualquier navegador web con soporte para formatos gráficos jpeg y webp. Para el uso de la aplicación será necesario registrarse creando una cuenta de usuario.   El usuario se responsabiliza de que los datos configurados en su cuenta son veraces y completos, no siendo en ningún caso la Empresa responsable del mal funcionamiento de la aplicación por ser dichos datos falsos o inexactos.
        <h6 class="mt-2">5. GARANTÍAS Y RESPONSABILIDAD</h6>
        La Empresa no garantiza que los servicios sean ininterrumpidos, proporcionados en tiempo oportuno, seguros o libres de errores.  El usuario entiende, y acepta expresamente, que utiliza la aplicación bajo su propio riesgo y responsabilidad.  Así mismo acepta que la Empresa no se compromete ni se responsabiliza con ninguna persona o entidad, respecto a cualquier perjuicio supuestamente provocado por el uso, tanto directa o indirectamente, incluyendo (sin estar limitado solo a ello), interrupciones del trabajo, pérdidas económicas, pérdida de información, fallo informático o cualquier otra pérdida derivada del uso o no uso del mismo.    Toda la responsabilidad de la Empresa hacia el usuario de la aplicación, en ningún caso excederá de las tarifas pagadas por el usuario por el acceso a la aplicación durante el periodo de la incidencia. 
        
        El uso de cualquier material descargado u obtenido a través de la utilización de la plataforma se realiza bajo la responsabilidad y riesgo del usuario.  El usuario es el único responsable de cualquier daño de su sistema informático, ordenador, teléfono móvil, tableta, dispositivo digital o datos dañados (propios o de terceros a los que el usuario haya dado acceso) que resulte del uso de la aplicación o de la descarga de material a través de la misma. 
        
        Ninguna sugerencia, consejo o información, ya sea oral o por escrito, obtenida de la Empresa, sus empleados o sus representantes, creará ninguna garantía que no esté expresamente establecida en estos términos y condiciones.    
        <h6 class="mt-2">6. TARIFAS, PAGOS Y REEMBOLSOS</h6>
        Los usuarios podrán adherirse a planes de suscripción de diferentes duraciones.   Los planes vigentes estarán publicados en todo momento en la web comercial de la aplicación www.ohmyphoto.es.    Estos planes serán abonados mediante tarjeta de crédito.   Su suscripción se renovará automáticamente al final de cada período de suscripción, a menos que se cancele la suscripción antes de la finalización del periodo contratado, y la renovación será cargada a la última tarjeta que utilizó, pudiendo actualizar los datos de la misma antes del cargo del próximo periodo.    
        El usuario dispondrá de un mes de prueba. No se facturará ningún importe hasta que no se adhiera a un plan de suscripción de pago.   Al disponer de un periodo de prueba de un mes, no se podrá efectuar reembolso alguno una vez abonado el importe de la suscripción con la periodicidad elegida, pero siempre podrá cancelar la suscripción en cualquier momento, permitiéndole su uso hasta el final del periodo contratado. 
        La Empresa se reserva el derecho de modificar el precio de la aplicación o cobrar por el uso de funcionalidades previamente disponibles de forma gratuita. Cualquier aumento de tarifa solo se aplicará después del vencimiento de su ciclo de facturación actual en el momento en que se anuncie. 
        Una vez cancelada su suscripción o la terminación de su periodo de prueba sin que se haya adherido a ningún plan de suscripción, la aplicación conservará los datos de su cuenta durante 30 días, pudiendo solicitar una copia de sus datos, y después será eliminada borrando con ellos todos los datos asociados a su usuario.
        <h6 class="mt-2">7. CONTENIDO GENERADO POR EL USUARIO</h6>
        El usuario puede transmitir o publicar contenido que cree utilizando la aplicación. Dicho esto, el usuario asume toda la responsabilidad por este contenido y las consecuencias de su transmisión o publicación. Cualquier contenido hecho público, al ser accesible a todos en Internet, es susceptible de ser analizado e indexado por los motores de búsqueda. Es responsabilidad del usuario asegurarse de no poner a disposición del público ningún contenido privado sin darse cuenta o intencionadamente.        
        
        Queda totalmente prohibida la subida a la aplicación de imágenes con derechos de autor, material ilegal, difamatorio, acosador, amenazante, dañino, pornografía o que hagan apología del racismo, antisemitismo, terrorismo, o cualquier otra imagen que vulnere los derechos de las personas o de la propiedad intelectual.   Asimismo, no podrán subirse archivos que contengan virus o códigos maliciosos. No se podrá utilizar la aplicación para enviar spam, correos basura, distribución masiva de correo electrónico no solicitado o lanzar ataques de phishing.
        
        En caso de que la Empresa detecte alguna de las actividades mencionadas, o el uso malicioso de la aplicación, se reserva el derecho a suprimir la cuenta y borrar toda su información. 
        <h6 class="mt-2">8. PROPIEDAD DE LOS DATOS</h6>
        El usuario será el propietario de los datos que cree o almacene en la aplicación.    A menos que se autorice expresamente el uso de los datos de la aplicación, no le otorga a la Empresa el derecho de usar, reproducir, adaptar, modificar, publicar o distribuir cualquier contenido que haya creado o almacenado en su cuenta de usuario para sus propios fines comerciales y de marketing o similares. Sin embargo, usted autoriza a la Empresa a consultar, copiar, distribuir, almacenar, transmitir, reformatear el contenido de su cuenta de usuario exclusivamente con el fin de proporcionarle el servicio de utilización de la aplicación. 
        <h6 class="mt-2">9. RESTRICCIONES DE USO</h6>
        Además de todos los demás términos de uso establecidos en este Acuerdo, usted no puede: (i) transferir ni poner la aplicación a disposición de ningún tercero; (ii) proporcionar cualquier servicio basado en la aplicación sin consentimiento previo por escrito; (iii) utilizar enlaces a sitios web de terceros sin aceptar sus términos de uso; (iv) publicar enlaces a sitios de terceros o utilizar su logotipo, nombre de empresa, etc. sin obtener su consentimiento previo por escrito; (v) publicar información personal o confidencial perteneciente a cualquier persona o entidad sin obtener su consentimiento; (vi) utilizar la aplicación de cualquier manera que pueda dañar, deshabilitar, sobrecargar, interrumpir o de otro modo perjudicar los servidores, redes, sistemas informáticos o recursos de la empresa; (vii) violar cualquier ley local, regional, nacional o internacional aplicable; y (viii) crear una identidad falsa con el fin de engañar a cualquier persona sobre el origen de una comunicación o la identidad de su remitente.
        <h6 class="mt-2">10. USUARIOS TESTERS</h6>
        La Empresa se reserva el derecho de ofrecer acceso gratuito a usuarios TESTER seleccionados por ella que utilizarán la aplicación en versiones beta con fines de prueba y evaluación, cuyo compromiso será el de reporte de errores o sugerencia de mejoras.   Los usuarios TESTERS aceptan y asumen que están trabajando en un entorno de prueba y no podrán realizar reclamación alguna a la Empresa por cualquier daño causado por el incorrecto funcionamiento de la aplicación beta.    Los usuarios TESTER aceptan que la Empresa tiene plena autoridad y exclusivo criterio para establecer el período de tiempo asignado para las pruebas y evaluación de la aplicación beta.   Sólo la Empresa puede juzgar el éxito de estas pruebas y decidir ofrecer o no la aplicación beta como aplicación comercial.  La Empresa se reserva el derecho de desistir, total o parcialmente, en cualquier momento, temporal o permanentemente, de cualquier funcionalidad que se esté implementando en la aplicación beta, con o sin previo aviso. Los usuarios beta aceptan que la Empresa no es responsable ante ellos ni ante terceros por ningún daño asociado, que surja o sea causado por la modificación, suspensión o discontinuación de la aplicación beta en su totalidad o de una funcionalidad concreta de la aplicación beta por cualquier motivo.  Tanto la Empresa como el usuario TESTER, puede rescindir en cualquier momento esta colaboración, con un preaviso de 15 días, y pasar a ser usuarios de la aplicación comercial.     Por lo demás, los usuarios TESTERS se regirán por el resto de términos y condiciones contemplados en el presente Acuerdo. 
        <h6 class="mt-2">11. COMUNICACIONES</h6>
        El usuario acepta expresamente que la Empresa pueda enviarle comunicaciones vía email, telefónica o por mensajería instantánea tales como emails de flujo de trabajos, comunicaciones informativas, novedades, mensajes administrativos, etc.     El usuario asume que forma parte del uso integral de la plataforma y no podrá oponerse a ellas.     Asimismo, el usuario sí que podrá indicar que no desea recibir comunicaciones meramente comerciales por parte de la Empresa. 
        
        De la misma forma el usuario podrá ponerse en contacto por la empresa, para resolver dudas o reportar alguna incidencia, a través del correo electrónico info@ohmyphoto.es, o por cualquiera de los medios de contacto que en ese momento estén publicados en la web de la aplicación www.ohmyphoto.es
        
        Toda comunicación entre las partes será tratada de forma confidencial.
        <h6 class="mt-2">12. PRIVACIDAD Y PROTECCIÓN DE DATOS</h6>
        El usuario es el responsable de mantener la confidencialidad de su nombre de usuario, contraseña y otra información confidencial en su poder. El usuario asume la responsabilidad de todas las actividades que ocurren en su cuenta de usuario y acepta notificarnos inmediatamente sobre cualquier uso no autorizado de su cuenta de usuario, enviándonos un correo electrónico a info@ohmyphoto.es. La Empresa no se hace responsable de ninguna pérdida o daño que el usuario (o cualquier tercero) pueda sufrir como resultado del acceso no autorizado a su cuenta y/o cualquier otro uso no autorizado de la misma.
        
        En cumplimiento de la Ley de Servicios de la Sociedad de la Información de Comercio Electrónico (LSSICE) y de la normativa vigente en materia de Protección de Datos de Carácter Personal, el usuario acepta que los datos facilitados por él, serán incorporados a un fichero automatizado cuyo responsable es la Empresa con el fin de gestionar las relaciones comerciales entre las partes.  La Empresa se compromete a no ceder datos a terceros, excepción hecha de las empresas de su grupo. Al usuario se le reconoce el derecho de acceso, rectificación, limitación de tratamiento, portabilidad y oposición / revocación que podrá ejercer en la dirección C/ Alfonso X El Sabio, 13, 1°A, 30205 Cartagena, o en el correo electrónico info@ohmyphoto.es
        <h6 class="mt-2">13. SUSPENSIÓN Y TERMINACIÓN</h6>
        La Empresa puede suspender una cuenta de usuario o desactivar temporalmente el acceso a parte o la totalidad de la aplicación en caso de sospecha de actividad ilegal, períodos prolongados de inactividad o solicitudes de las autoridades encargadas de hacer cumplir la ley u otras agencias gubernamentales. Las disputas sobre la suspensión o desactivación de cuentas de usuario deben enviarse a info@ohmyohoto.es dentro de los treinta días posteriores a la notificación de la suspensión. La Empresa puede eliminar una cuenta de usuario suspendida o deshabilitada después de treinta días. La Empresa también puede eliminar una cuenta de usuario si el usuario lo solicita.
        
        Además, la Empresa se reserva el derecho de eliminar una cuenta de usuario y prohibirle el uso de la aplicación si la misma encuentra motivos razonables para creer que el usuario ha violado los términos y condiciones de este Acuerdo.   En el caso de usuarios TESTER, la Empresa puede cancelar su acceso a la aplicación beta en caso de problemas técnicos o inesperados o por el cierre de la aplicación beta.
        
        Serán motivos suficientes para la extinción de este acuerdo, el incumplimiento por el usuario de alguno de los términos o condiciones que aquí se recogen, el uso de la aplicación con fines ilícitos, o el impago de las cuotas de la suscripción, en ese caso, la misma quedará bloqueada hasta su regularización, en caso de superar los 30 días sin dicha regularización, la cuenta será eliminada y el usuario no tendrá derecho a la reclamación de sus datos si no solicitó una copia de los mismos durante ese periodo.  
        
        
        El usuario tiene derecho a cancelar su cuenta si la Empresa incumple sus obligaciones según estos términos y condiciones. En tales circunstancias, el usuario tendrá derecho a un reembolso calculado en proporción a los costes que haya pagado por adelantado. La cancelación de una cuenta de usuario da como resultado la prohibición del acceso a la aplicación, la eliminación de la información de la cuenta de usuario, así como la dirección de correo electrónico y contraseña, y la eliminación de todos los demás datos de la cuenta de usuario. 
        <h6 class="mt-2">14. EXCLUSIONES</h6>
        Son nulos y sin ningún valor cualesquiera compromisos o pactos adicionales a este Acuerdo, escritos o verbales, que no se fijen expresamente en el mismo. La Empresa no se responsabilizará de demora o incumplimiento del Acuerdo causada por circunstancias ajenas a su voluntad o control, entre las que figuran, sin que la mención sea limitada, la cesación de trabajo, guerras, huelgas, conflictos laborales, incendios, inundaciones, resistencia pasiva, desórdenes, restricciones impuestas por las Autoridades, incumplimiento por parte de los proveedores de servicios que tiene contratados la Empresa y otros casos fortuitos o de fuerza mayor. Si alguno los términos y condiciones del presente Acuerdo fuese contraria a cualquier norma vigente que le sea de aplicación o fuese declarada nula por cualquier Tribunal español, se entenderá por no puesto, sin afectar al resto del Acuerdo.
        <h6 class="mt-2">15. JURISDICCIÓN</h6>
        Las partes renuncian expresamente a su propio fuero si lo tuvieran y se someten a los Juzgados y Tribunales de Cartagena, respecto a cualquier discrepancia que pudiera surgir en la interpretación y cumplimiento del presente Acuerdo.  No se han efectuado acuerdos verbales válidos y el presente documento con sus QUINCE apartados que recogen los TÉRMINOS DE LICENCIA Y CONDICIONES DE USO, conforman la totalidad del convenio interpartes, aceptando ambas todo lo expuesto sin reservas. 



        </div>
        <div class="col-12 col-md-12 text-center oculto">
            <a rel="tooltip" class="btn botonoh_negro"
            onclick="history.back()" title="Volver">
            <i class="material-icons">undo</i>&nbsp;Volver
            </a>
        </div>
    </div>
</div>

<!--   Core JS Files   -->
@push('js')
    <script src="{{ asset('assets') }}/js/plugins/perfect-scrollbar.min.js"></script>
@endpush
